spring:
  application:
    name: cloud-stream
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud
    password: 123456
    virtual-host: cloud
  cloud:
    stream:
      bindings:
        input:
          destination: raw-sensor-data
server:
  port: 8889
