spring:
  application:
    name: eureka-client
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud
    password: 123456
    virtual-host: cloud
  zipkin:
    rabbitmq:
      queue: zipkin
#    base-url: http://localhost:9411
server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/