spring:
  application:
    name: eureka-consumer-feign
  sleuth:
    sampler:
      # 即100%的概率将链路的数据上传给Zipkin Server
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
server:
  port: 2101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/