spring:
  application:
    name: zipkin-server
server:
  port: 9411
#  zipkin通过rabbitMQ收集跟踪信息
zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      username: cloud
      password: 123456
      queue: zipkin
      virtual-host: cloud